; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; --- סירה: ארדואינו עם מנועים וחיישנים ---
[env:boat]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = COM4
lib_deps =
    mikem/RadioHead
    nabontra/ServoTimer2
src_filter = +<main.cpp>

; --- חוף: ארדואינו המחובר למחשב ---
[env:shore]
platform = atmelavr
board = uno
framework = arduino
upload_port = COM4
lib_deps =
    mikem/RadioHead
src_filter = +<shore_radio.cpp>
